[package]
name = "csv_to_embedding_vectors"
version = "0.1.0"
authors = ["sudoQuigley <sanskars@icloud.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
